language: ruby
cache: bundler
bundler_args: "--without production"
rvm:
- 2.7.0
before_install:
- gem install bundler:2.2.11
script:
- bundle exec rspec
deploy:
  provider: heroku
  app: fast-waters-11904
  api_key:
    secure: F7gkrRkdhtdKaF0kggqVKSpEAnNQb4ophKOcrd9Sh3fnoY2w5WKUeuJX1yNZylGNN/c25zYiG5rFSXn44XgYeqw2e8dnYAfVQB1VrXvDqBLn4veP7s9cjPOZ9xxCTBStebUrqYjTonZpzuGTifxV40nby/o+n+KBSfNe9Y9KmN8H8cN5w+TRDc9cZlRQDSqg7FK8064RLoNOi7PzIOwI/CHMJyc6wo5GrzGl31/yMMJWWaoum4Fi6H+K7RT6ibk9QlfHiTP8rxVMaCKjF1kspnrVLx21rNDeX3kIynJWcooquHAw1h716eeKXAenaoR88Xr4SIMrRUZJ6iYQet4UtLnp7/1wYQOg7GTs5GwsPtz3zMYZPhn3nAPQlr1GQsf/NKumrYTNCF6YZjqO3lJaEc3WkA3wL025UcQy6UworDoYj3Pb3IMyJPQMYJR9yY4Jq04xs6apetoxsm4YtOicv0VML1UeUyqhw6CF6/43QZEq0q8/XYfbSlbHRen30Ub5c/4zUeKDDNXZZyMaWMaFBbQy3y1WRX6Uzgl7wIdSkTIFfsvxrq1i9Sy8NAhb+sogin8B8FMgzc1HinC4ylYXhpLcYM56TVFoUX25MnCVvQ8TtAsJdIaePwpGukr3pjuTLBnspxttFDniygutplF5aTgHj/C9Fv4N9uvN208MKWU=
  run:
  - rake db:migrate
  - rake cleanup
  on: main
